// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-G0uaL-McV_q-miUfBmrEYNwfKORaucY',
    appId: '1:607995216337:web:1d9b85822f68e4255520f0',
    messagingSenderId: '607995216337',
    projectId: 'sparring-2721f',
    authDomain: 'sparring-2721f.firebaseapp.com',
    storageBucket: 'sparring-2721f.firebasestorage.app',
    measurementId: 'G-3JDLJBGER6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-BvQYE-QVOvUxJcn_qt_RrYdWk3U22qk',
    appId: '1:607995216337:android:ee4c53c1d83cbb1a5520f0',
    messagingSenderId: '607995216337',
    projectId: 'sparring-2721f',
    storageBucket: 'sparring-2721f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVCFjwQUnZpZhmvrHJA_c1Su1tromA5l8',
    appId: '1:607995216337:ios:cc67a25801934fae5520f0',
    messagingSenderId: '607995216337',
    projectId: 'sparring-2721f',
    storageBucket: 'sparring-2721f.firebasestorage.app',
    iosBundleId: 'com.arraya.sparring',
  );
}
